# app/email_notifier.py
# Optional email notification support for digest delivery

import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional

logger = logging.getLogger(__name__)

# SMTP Configuration from environment
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
EMAIL_FROM = os.getenv("EMAIL_FROM", SMTP_USER)


def is_email_configured() -> bool:
    """Check if email notifications are configured."""
    return bool(SMTP_USER and SMTP_PASSWORD)


def send_digest_email(
    to_email: str,
    subject: str,
    content: str,
    html_content: Optional[str] = None
) -> bool:
    """
    Send a digest email to the specified address.
    
    Args:
        to_email: Recipient email address
        subject: Email subject line
        content: Plain text email content
        html_content: Optional HTML version of the content
        
    Returns:
        True if sent successfully, False otherwise
    """
    if not is_email_configured():
        logger.warning("Email not configured. Skipping email notification.")
        return False
    
    try:
        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = EMAIL_FROM
        msg["To"] = to_email
        
        # Attach plain text version
        part1 = MIMEText(content, "plain", "utf-8")
        msg.attach(part1)
        
        # Attach HTML version if provided
        if html_content:
            part2 = MIMEText(html_content, "html", "utf-8")
            msg.attach(part2)
        
        # Send email
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(EMAIL_FROM, to_email, msg.as_string())
        
        logger.info(f"Email sent successfully to {to_email}")
        return True
        
    except Exception as e:
        logger.error(f"Failed to send email to {to_email}: {e}")
        return False


def send_weekly_digest_email(
    to_email: str,
    topic: str,
    digest_content: str
) -> bool:
    """
    Send a formatted weekly digest email.
    
    Args:
        to_email: Recipient email address
        topic: Topic of the digest
        digest_content: The digest content
        
    Returns:
        True if sent successfully, False otherwise
    """
    subject = f"📊 Your Weekly {topic.title()} Digest - Reddit Digest Bot"
    
    # Create HTML version
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                       color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; }}
            .content {{ padding: 20px; background: #f9f9f9; border-radius: 10px; }}
            .footer {{ margin-top: 20px; font-size: 12px; color: #666; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>📊 Weekly {topic.title()} Digest</h1>
        </div>
        <div class="content">
            <pre style="white-space: pre-wrap; font-family: inherit;">{digest_content}</pre>
        </div>
        <div class="footer">
            <p>This digest was generated by Reddit Digest Bot.</p>
            <p>Reply to change your preferences or unsubscribe.</p>
        </div>
    </body>
    </html>
    """
    
    return send_digest_email(to_email, subject, digest_content, html_content)


def send_daily_digest_email(
    to_email: str,
    topic: str,
    digest_content: str
) -> bool:
    """
    Send a formatted daily digest email.
    """
    subject = f"📅 Your Daily {topic.title()} Digest - Reddit Digest Bot"
    
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .header {{ background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); 
                       color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; }}
            .content {{ padding: 20px; background: #f9f9f9; border-radius: 10px; }}
            .footer {{ margin-top: 20px; font-size: 12px; color: #666; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>📅 Daily {topic.title()} Digest</h1>
        </div>
        <div class="content">
            <pre style="white-space: pre-wrap; font-family: inherit;">{digest_content}</pre>
        </div>
        <div class="footer">
            <p>This digest was generated by Reddit Digest Bot.</p>
        </div>
    </body>
    </html>
    """
    
    return send_digest_email(to_email, subject, digest_content, html_content)
